### ISSUE TITLE
Variable names

### ISSUE THREAD

**Issue by stroup-tmu** [bennettapps/assettracker#1]
Hi Jesse!

First issue: let's make these variable names consistent. It should be plural for an array (e.g. @employees = Employee.all)

https://github.com/bennettapps/assettracker/blob/7b7695fdd3d5d83286b96f1d8f500dd5c9bc98bf/app/controllers/dashboard_controller.rb#L3

**Comment by bennettapps** [comment]
Good catch! Pushed this change.

Jesse
