### ISSUE TITLE
Scoped queries

### ISSUE THREAD

**Issue by stroup-tmu** [bennettapps/assettracker#2]
Second issue: If you have configured your relationships in your models correctly, you should be able to execute a scoped query for devices of that category directly from the category model. E.g. "category.devices..." Take a shot at it!

https://github.com/bennettapps/assettracker/blob/7b7695fdd3d5d83286b96f1d8f500dd5c9bc98bf/app/views/dashboard/index.html.erb#L17

**Comment by bennettapps** [comment]
Hi,
This works for software.employees because software has many employees, but it's throwing an error undefined for category.devices because the way I have my models set up now, categories don't have many devices, devices simply have one category. Is this incorrect? It seems to work fine.

**Comment by stroup-tmu** [comment]
Hi Jesse! Yes, it is throwing an error now because it is not defined yet in the model. So you need to define the "devices" relationship within the Category model first, and then you can execute it here in the dashboard page.

**Comment by stroup-tmu** [comment]
Sorry, so to answer your question, "has_many" is simply the opposite of "belongs_to", so you should be able to define the has_many from the other side in the Category model too.

**Comment by bennettapps** [comment]
Understood. Just pushed!
