### ISSUE TITLE
Employees (plural)

### ISSUE THREAD

**Issue by stroup-tmu** [bennettapps/assettracker#3]
Last thing: "employees" should be plural here, since it is a HABTM relationship. Change it here, and then update it where needed in your views as well.

https://github.com/bennettapps/assettracker/blob/7b7695fdd3d5d83286b96f1d8f500dd5c9bc98bf/app/models/software.rb#L2

**Comment by bennettapps** [comment]
Good point. Many should be plural obviously. Just pushed the change.
